# Generated by Django 5.2.13 on 2026-04-29 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0019_alter_schoolfeature_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('highest_qualification', models.CharField(choices=[('ssce', 'SSCE / WASSCE'), ('diploma', 'Diploma / HND'), ('degree', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD / Doctorate'), ('professional', 'Professional Certificate'), ('other', 'Other')], default='degree', max_length=20)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('current_employer', models.CharField(blank=True, max_length=200)),
                ('subjects_taught', models.CharField(blank=True, help_text='Subjects able to teach', max_length=255)),
                ('cover_letter', models.TextField()),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=10)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='pending_payment', max_length=25)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('mode', models.CharField(choices=[('in_person', 'In Person'), ('video_call', 'Video Call'), ('phone', 'Phone Interview')], default='in_person', max_length=15)),
                ('location', models.CharField(blank=True, help_text="Physical address or 'Online'", max_length=300)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom / Google Meet / Teams link')),
                ('message_to_applicant', models.TextField(help_text='Personal message included in the interview invitation')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedule', to='recruitment.jobapplication')),
            ],
            options={
                'ordering': ['interview_date', 'interview_time'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(help_text='e.g. Mathematics Teacher, Deputy Head', max_length=150)),
                ('job_type', models.CharField(choices=[('teacher', 'Teacher'), ('hod', 'Head of Department'), ('admin', 'Administration Staff'), ('support', 'Support Staff'), ('other', 'Other')], default='teacher', max_length=20)),
                ('subjects', models.CharField(blank=True, help_text='Relevant subjects, comma-separated', max_length=255)),
                ('description', models.TextField(help_text='Full role description')),
                ('requirements', models.TextField(help_text='Minimum qualifications and requirements')),
                ('salary_range', models.CharField(blank=True, help_text='e.g. GHS 1,500 – 2,500 / month', max_length=100)),
                ('slots_available', models.PositiveSmallIntegerField(default=1)),
                ('application_fee', models.DecimalField(decimal_places=2, default=50.0, help_text='Platform application fee in GHS (goes to Mastex platform)', max_digits=10)),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_postings', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobposting'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['school', 'is_active', 'deadline'], name='idx_jobposting_school_active'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='idx_jobapp_job_status'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'payment_status'], name='idx_jobapp_job_payment'),
        ),
    ]
