[pytest]
DJANGO_SETTINGS_MODULE = schoolms.settings_e2e
python_files = test_*.py
testpaths = e2e_tests
addopts = -v --tb=short --strict-markers -p no:anyio -p no:playwright
markers =
    django_db: Django DB access (pytest-django)
