# Generated by Django 6.0.3 on 2026-03-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_add_partial_payments_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=1500, help_text='Monthly subscription fee in GHS', max_digits=12),
        ),
    ]
