# Generated by Django 6.0.3 on 2026-04-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_remove_school_flutterwave_tx_ref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='schoolfeature',
            options={'ordering': ['key'], 'verbose_name': 'School Feature', 'verbose_name_plural': 'School Features'},
        ),
    ]
