# Generated by Django 6.0.3 on 2026-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_schoolfeature_staff_paystack_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subscription_grace_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days after subscription_end_date before access is fully blocked (read-only / renew flows still allowed).'),
        ),
    ]
