# Generated by Django 5.2.13 on 2026-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_school_timezone_email_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ai_monthly_token_cap',
            field=models.PositiveIntegerField(default=0, help_text='Maximum AI tokens allowed per school per calendar month. 0 = unlimited.'),
        ),
    ]
