# Generated by Django 5.2.13 on 2026-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_schoolnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='currency',
            field=models.CharField(default='GHS', help_text='ISO 4217 currency code for this school (e.g. GHS, NGN, KES, ZAR).', max_length=3),
        ),
    ]
