# Generated by Django 5.2.13 on 2026-04-12 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0011_erp_enhancements_batch1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for admins (e.g. Finance Slack)', max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('signing_secret', models.CharField(blank=True, help_text='Leave blank to auto-generate. Store securely — used to sign webhook payloads.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_staff_leave', models.BooleanField(default=True, help_text='Leave submitted / reviewed')),
                ('notify_expense', models.BooleanField(default=True, help_text='Expense created or updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'is_active'], name='idx_webhook_school_active')],
            },
        ),
    ]
