# Generated by Django 5.2.13 on 2026-04-19 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial_school_webhook_endpoint'),
        ('schools', '0011_erp_enhancements_batch1'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='integrations.schoolwebhookendpoint')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_delivery_attempts', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='idx_wh_attempt_status_retry'), models.Index(fields=['school', 'event_type', 'created_at'], name='idx_wh_attempt_school_event')],
            },
        ),
    ]
