# Generated by Django 5.2.13 on 2026-05-03 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0001_initial'),
        ('schools', '0020_alter_schoolfeature_key_choices'),
        ('students', '0020_erp_new_models_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OmrExamSectionB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, help_text='Used when student FK is not set (name-based matching).', max_length=200)),
                ('section_b_max_score', models.FloatField(default=40.0, help_text='Maximum marks for Section B.')),
                ('section_b_score', models.FloatField(default=0.0)),
                ('section_a_omr_score', models.FloatField(blank=True, help_text='Cached Section A score from OmrResult (auto-filled, read-only).', null=True)),
                ('section_a_max_score', models.FloatField(blank=True, help_text='Cached Section A max from OmrExam total_questions.', null=True)),
                ('section_a_override', models.FloatField(blank=True, help_text='Teacher correction of the OMR-detected Section A score.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omr_section_b_created', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_b_scores', to='omr.omrexam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omr_section_b_scores', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omr_section_b_scores', to='students.student')),
            ],
            options={
                'verbose_name': 'OMR Section B Score',
                'verbose_name_plural': 'OMR Section B Scores',
                'ordering': ['student_name'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
