# Generated by Django 5.2.13 on 2026-05-04 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0002_omrexamsectionb'),
        ('schools', '0020_alter_schoolfeature_key_choices'),
        ('students', '0020_erp_new_models_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='omrexamsectionb',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', True)), fields=('exam', 'student_name'), name='uniq_omrsectionb_exam_name_nostu'),
        ),
    ]
