# Generated by Django 5.2.13 on 2026-05-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0003_omrexamsectionb_uniq_omrsectionb_exam_name_nostu'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrexam',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
