from django.urls import path
from .views import (
    parent_dashboard,
    student_list,
    student_detail,
    student_edit,
    student_register,
    student_delete,
    student_exit,
    student_clearance,
    student_reactivate,
    promote_students,
    bulk_student_status,
    graduate_class,
    class_list,
    class_create,
    announcements_list,
    fees_list,
    results_list,
    parent_child_detail,
    absence_request_create,
    my_absence_requests,
    parent_absence_request_create,
    parent_absence_requests,
    absence_requests_review,
    absence_request_decide,
    student_guardian_add,
    student_guardian_remove,
    learning_plan_list,
    learning_plan_create,
    learning_plan_detail,
    learning_plan_delete,
)

app_name = "students"

urlpatterns = [
    path("parent-dashboard/", parent_dashboard, name="parent_dashboard"),
    path("announcements/", announcements_list, name="announcements_list"),
    path("fees/", fees_list, name="fees_list"),
    path("results/", results_list, name="results_list"),
    path("children/<int:pk>/", parent_child_detail, name="parent_child_detail"),
    path("list/", student_list, name="student_list"),
    path("detail/<int:pk>/", student_detail, name="student_detail"),
    path("edit/<int:pk>/", student_edit, name="student_edit"),
    path("register/", student_register, name="student_register"),
    path("delete/<int:pk>/", student_delete, name="student_delete"),
    path("reactivate/<int:pk>/", student_reactivate, name="student_reactivate"),
    path("clearance/<int:pk>/", student_clearance, name="student_clearance"),
    path("exit/<int:pk>/", student_exit, name="student_exit"),
    path("promote/", promote_students, name="promote_students"),
    path("bulk-status/", bulk_student_status, name="bulk_student_status"),
    path("graduate-class/", graduate_class, name="graduate_class"),
    path("classes/", class_list, name="class_list"),
    path("classes/create/", class_create, name="class_create"),
    # Student absence requests
    path("absence/request/", absence_request_create, name="absence_request_create"),
    path("absence/my/", my_absence_requests, name="my_absence_requests"),
    # Parent absence requests (for linked children)
    path("absence/children/request/", parent_absence_request_create, name="parent_absence_request_create"),
    path("absence/children/", parent_absence_requests, name="parent_absence_requests"),
    path("absence/review/", absence_requests_review, name="absence_requests_review"),
    path(
        "absence/<int:pk>/decide/",
        absence_request_decide,
        name="absence_request_decide",
    ),
    # Guardian management
    path("<int:pk>/guardians/add/", student_guardian_add, name="student_guardian_add"),
    path("guardians/<int:guardian_pk>/remove/", student_guardian_remove, name="student_guardian_remove"),
    # Learning Plans (F7)
    path("learning-plans/", learning_plan_list, name="learning_plan_list"),
    path("<int:student_pk>/learning-plans/create/", learning_plan_create, name="learning_plan_create"),
    path("learning-plans/<int:pk>/", learning_plan_detail, name="learning_plan_detail"),
    path("learning-plans/<int:pk>/delete/", learning_plan_delete, name="learning_plan_delete"),
]
