# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_add_expense_discipline_exam_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentidcard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
    ]
