# Generated by Django 6.0.3 on 2026-03-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='academiccalendar',
            name='ops_academicca_school_start_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='ops_activitylog_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignmentsubmission',
            name='ops_assignments_homework_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='behaviorpoint',
            name='ops_behaviorpo_school_awarded_idx',
        ),
        migrations.RemoveIndex(
            model_name='buspayment',
            name='ops_buspayment_school_paid_idx',
        ),
        migrations.RemoveIndex(
            model_name='canteenpayment',
            name='ops_canteenpay_school_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='disciplineincident',
            name='ops_discipline_school_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='disciplineincident',
            name='ops_discipline_student_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='examattempt',
            name='ops_examattempt_exam_student_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='ops_expense_school_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='healthvisit',
            name='ops_healthvisit_school_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='hostelfee',
            name='ops_hostelfee_school_paid_idx',
        ),
        migrations.RemoveIndex(
            model_name='libraryissue',
            name='ops_libraryissue_school_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='libraryissue',
            name='ops_libraryissue_student_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='onlineexam',
            name='ops_onlineexam_school_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffleave',
            name='ops_staffleave_school_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffleave',
            name='ops_staffleave_school_start_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentattendance',
            name='ops_studentatte_school_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentattendance',
            name='ops_studentatte_student_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacherattendance',
            name='ops_teacheratte_school_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacherattendance',
            name='ops_teacheratte_teacher_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='timetableslot',
            name='ops_timetableslo_school_class_idx',
        ),
    ]
