# Generated by Django 6.0.3 on 2026-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_add_payment_reference_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelfee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hostelfee',
            name='payment_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
