# Generated by Django 6.0.3 on 2026-04-09 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_add_amount_paid_field'),
        ('schools', '0008_alter_school_options_alter_schoolfeature_options'),
        ('students', '0009_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-date'], 'verbose_name': 'Student Attendance', 'verbose_name_plural': 'Student Attendance Records'},
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['school', 'date'], name='idx_att_school_date'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['school', 'date', 'status'], name='idx_att_school_date_status'),
        ),
    ]
