# Generated by Django 6.0.3 on 2026-04-09 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_alter_studentattendance_options_and_more'),
        ('schools', '0008_alter_school_options_alter_schoolfeature_options'),
        ('students', '0009_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('school', 'teacher', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('school', 'class_name', 'day', 'period_number')},
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['school', 'status'], name='idx_admission_school_st'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['school', 'target_audience', 'is_pinned'], name='idx_ann_school_aud_pin'),
        ),
        migrations.AddIndex(
            model_name='buspayment',
            index=models.Index(fields=['school', 'student'], name='idx_bus_school_stu'),
        ),
        migrations.AddIndex(
            model_name='canteenpayment',
            index=models.Index(fields=['school', 'student'], name='idx_canteen_school_stu'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['school', 'expense_date'], name='idx_expense_school_date'),
        ),
        migrations.AddIndex(
            model_name='hostelassignment',
            index=models.Index(fields=['school', 'student', 'is_active'], name='idx_hostelasn_sch_stu'),
        ),
        migrations.AddIndex(
            model_name='libraryissue',
            index=models.Index(fields=['school', 'student'], name='idx_libissue_school_stu'),
        ),
        migrations.AddIndex(
            model_name='libraryissue',
            index=models.Index(fields=['school', 'return_date'], name='idx_libissue_school_ret'),
        ),
        migrations.AddIndex(
            model_name='staffleave',
            index=models.Index(fields=['school', 'staff'], name='idx_leave_school_staff'),
        ),
        migrations.AddIndex(
            model_name='textbooksale',
            index=models.Index(fields=['school', 'student'], name='idx_txtsale_school_stu'),
        ),
    ]
