# Generated by Django 6.0.3 on 2026-04-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_alter_teacherattendance_unique_together_and_more'),
        ('students', '0010_student_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni', to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='students.schoolclass'),
        ),
    ]
