# Generated by Django 6.0.3 on 2026-04-09 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_alumni_school_class_timetableslot_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffidcard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_id_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='studentidcard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
