# Generated by Django 6.0.3 on 2026-04-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_alter_examquestion_correct_answer'),
        ('students', '0011_backfill_school_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='max_attempts_per_student',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum completed attempts per student (e.g. 3 for practice). Staff can still reset an attempt.'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'student', 'is_completed'], name='ops_exmatt_ex_st_done'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'attempt_number'), name='ops_exmatt_ex_stu_attn_uniq'),
        ),
    ]
