# Generated by Django 6.0.3 on 2026-04-10 04:32

from django.db import migrations, models


def _essay_flags(apps, schema_editor):
    ExamAnswer = apps.get_model("operations", "ExamAnswer")
    ExamAnswer.objects.filter(question__question_type="essay").update(teacher_reviewed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_exam_multi_attempt_quiz_retakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='teacher_reviewed',
            field=models.BooleanField(default=True, help_text='False for essay answers until a teacher enters marks.'),
        ),
        migrations.RunPython(_essay_flags, migrations.RunPython.noop),
    ]
