# Generated by Django 6.0.3 on 2026-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_sport_club_join_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='join_requires_approval',
            field=models.BooleanField(default=False, help_text='Student self-joins require sponsor or leadership approval before they appear on the roster.'),
        ),
        migrations.AlterField(
            model_name='club',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum approved members. Empty means no limit.', null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='join_requires_approval',
            field=models.BooleanField(default=False, help_text='Student self-joins require coach or leadership approval before they appear on the roster.'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum approved roster size. Empty means no limit.', null=True),
        ),
        migrations.AlterField(
            model_name='studentclub',
            name='pending_approval',
            field=models.BooleanField(default=False, help_text='Awaiting staff approval for student-initiated join.'),
        ),
        migrations.AlterField(
            model_name='studentsport',
            name='pending_approval',
            field=models.BooleanField(default=False, help_text='Awaiting staff approval for student-initiated join.'),
        ),
    ]
