# Generated by Django 6.0.3 on 2026-04-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_alter_club_join_requires_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('under_review', 'Under review'), ('interview', 'Interview / assessment'), ('documents_pending', 'Documents pending'), ('offered', 'Offer / provisional acceptance'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn by applicant'), ('approved', 'Approved / enrolled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
