# Generated by Django 6.0.3 on 2026-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_alter_admissionapplication_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='tab_blur_count',
            field=models.PositiveIntegerField(default=0, help_text='How often the exam tab lost visibility during this attempt (honesty signal).'),
        ),
    ]
