# Generated by Cascade on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0030_erp_enhancements_batch1"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="buspayment",
            constraint=models.UniqueConstraint(
                fields=["payment_reference"],
                condition=models.Q(payment_reference__isnull=False)
                & ~models.Q(payment_reference=""),
                name="uniq_buspayment_payment_reference_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="textbooksale",
            constraint=models.UniqueConstraint(
                fields=["payment_reference"],
                condition=models.Q(payment_reference__isnull=False)
                & ~models.Q(payment_reference=""),
                name="uniq_textbooksale_payment_reference_nonempty",
            ),
        ),
    ]
