# Generated by Cascade on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0031_uniq_payment_reference_nonempty"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hostelfee",
            constraint=models.UniqueConstraint(
                fields=["payment_reference"],
                condition=models.Q(payment_reference__isnull=False)
                & ~models.Q(payment_reference=""),
                name="uniq_hostelfee_payment_reference_nonempty",
            ),
        ),
    ]
