# Generated by Django 5.2.13 on 2026-04-19 22:34

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


def backfill_expense_status(apps, schema_editor):
    Expense = apps.get_model('operations', 'Expense')
    Expense.objects.filter(approved_by__isnull=False).update(status='approved')
    Expense.objects.filter(approved_by__isnull=True).update(status='submitted')


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0036_certificate_pdf_filefield'),
        ('schools', '0011_erp_enhancements_batch1'),
        ('students', '0015_unique_student_admission_number_per_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentdocument',
            managers=[
                ('scoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='submitted', help_text='Approval lifecycle state.', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='void_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='expense',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_expense_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='staffidcard',
            name='card_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentidcard',
            name='card_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['school', 'status'], name='idx_expense_school_status'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='chk_expense_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_invcategory_school_name'),
        ),
        migrations.AddConstraint(
            model_name='libraryissue',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['issued', 'overdue'])), fields=('student', 'book'), name='uniq_active_libissue_student_book'),
        ),
        migrations.AddConstraint(
            model_name='staffidcard',
            constraint=models.UniqueConstraint(fields=('school', 'card_number'), name='uniq_staffidcard_school_card_number'),
        ),
        migrations.AddConstraint(
            model_name='studentidcard',
            constraint=models.UniqueConstraint(fields=('school', 'card_number'), name='uniq_studentidcard_school_card_number'),
        ),
    ]
