# Generated by Django 5.2.13 on 2026-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0041_expense_recorded_by_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='payment_frequency',
            field=models.CharField(choices=[('term', 'Per Term'), ('daily', 'Daily')], default='term', max_length=10),
        ),
    ]
