# Generated by Django 5.2.13 on 2026-04-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0042_busroute_payment_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="buspayment",
            name="daily_units",
            field=models.PositiveIntegerField(
                default=0,
                help_text="For daily routes: number of days covered by this payment.",
            ),
        ),
    ]
