# Generated by Django 5.2.13 on 2026-04-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0044_merge_20260421_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenitem',
            name='category',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textbook',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='textbook',
            name='class_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='textbook',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='textbook',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
