# Generated by Django 5.2.13 on 2026-04-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0045_canteenitem_category_canteenitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='match_left',
            field=models.TextField(blank=True, help_text="Pipe-separated left-side items for matching questions, e.g. 'Item 1|Item 2|Item 3'."),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='match_right',
            field=models.TextField(blank=True, help_text="Pipe-separated right-side items for matching questions, e.g. 'Answer 1|Answer 2|Answer 3'."),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='option_e',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='option_f',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marks deducted per wrong answer for multi_select questions (0 = no penalty).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='answer_given',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='A–D for MCQ/T-F/dropdown; comma-separated letters for multi_select (e.g. A,C); JSON pairs for matching.', max_length=500),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('multi_select', 'Multi-Select (Checkboxes)'), ('dropdown', 'Dropdown'), ('matching', 'Matching')], max_length=20),
        ),
    ]
