# Generated by Django 5.2.13 on 2026-04-27 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0057_behaviorpoint_range_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['school_admin', 'deputy_head', 'hod', 'teacher', 'accountant', 'librarian', 'admission_officer', 'school_nurse', 'admin_assistant', 'staff']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
