# Generated by Django 5.2.13 on 2026-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0058_alter_teacherattendance_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity Log (Deprecated)', 'verbose_name_plural': 'Activity Logs (Deprecated — use Audit Logs)'},
        ),
        migrations.AddField(
            model_name='expense',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount before tax (amount - tax_amount).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Computed VAT amount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT/tax rate as percentage (e.g. 15.00 = 15%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Gross amount including tax.', max_digits=12),
        ),
    ]
