# Generated by Django 5.2.13 on 2026-04-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0059_alter_activitylog_options_expense_net_amount_and_more'),
        ('schools', '0018_school_currency'),
        ('students', '0019_student_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='degree_programme',
            field=models.CharField(blank=True, help_text='Degree or qualification (e.g. BSc Computer Science).', max_length=200),
        ),
        migrations.AddField(
            model_name='alumni',
            name='employer',
            field=models.CharField(blank=True, help_text='Current or most recent employer.', max_length=300),
        ),
        migrations.AddField(
            model_name='alumni',
            name='graduation_university_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='has_mentored_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumni',
            name='industry_sector',
            field=models.CharField(blank=True, help_text='e.g. Finance, Tech, Health, Education.', max_length=100),
        ),
        migrations.AddField(
            model_name='alumni',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumni',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='alumni',
            name='total_donations',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative donations to the school in GHS.', max_digits=14),
        ),
        migrations.AddField(
            model_name='alumni',
            name='university',
            field=models.CharField(blank=True, help_text='University / tertiary institution attended.', max_length=300),
        ),
        migrations.CreateModel(
            name='CanteenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(db_index=True, help_text='Date for which the food is being ordered.')),
                ('order_type', models.CharField(choices=[('preorder', 'Pre-Order'), ('walkin', 'Walk-In')], default='preorder', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready', 'Ready for Collection'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(blank=True, help_text='Linked payment once the order is paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canteen_order', to='operations.canteenpayment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_orders', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_orders', to='students.student')),
            ],
            options={
                'verbose_name': 'Canteen Order',
                'verbose_name_plural': 'Canteen Orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanteenOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='operations.canteenitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.canteenorder')),
            ],
            options={
                'verbose_name': 'Canteen Order Item',
                'verbose_name_plural': 'Canteen Order Items',
            },
        ),
        migrations.AddIndex(
            model_name='canteenorder',
            index=models.Index(fields=['school', 'order_date', 'status'], name='idx_corder_school_date_status'),
        ),
        migrations.AddIndex(
            model_name='canteenorder',
            index=models.Index(fields=['student', 'order_date'], name='idx_corder_stu_date'),
        ),
        migrations.AlterUniqueTogether(
            name='canteenorderitem',
            unique_together={('order', 'item')},
        ),
    ]
