# Generated by Django 5.2.13 on 2026-04-29 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0061_migrate_discipline_incidents'),
        ('schools', '0019_alter_schoolfeature_key'),
        ('students', '0020_erp_new_models_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Term 1 Classroom Supplies', max_length=200)),
                ('academic_year', models.CharField(blank=True, help_text='e.g. 2024/2025', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional instructions to parents')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_parents', models.BooleanField(default=True, help_text='Send in-app notification to parents when created')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supply_requests', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to='students.schoolclass')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassSupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Broom, Soap, Toilet Tissue', max_length=150)),
                ('quantity_per_student', models.PositiveSmallIntegerField(default=1, help_text='How many units each student is expected to bring')),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('pack', 'Pack'), ('roll', 'Roll'), ('bottle', 'Bottle'), ('box', 'Box'), ('bag', 'Bag'), ('pair', 'Pair'), ('litre', 'Litre'), ('other', 'Other')], default='piece', max_length=10)),
                ('notes', models.CharField(blank=True, help_text="e.g. 'Size A4', 'Brand does not matter'", max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.classsupplyrequest')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSupplyContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_brought', models.PositiveSmallIntegerField(default=1)),
                ('brought_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='operations.classsupplyitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_supply_contributions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_contributions', to='students.student')),
            ],
            options={
                'ordering': ['-brought_date'],
            },
        ),
        migrations.AddIndex(
            model_name='classsupplyrequest',
            index=models.Index(fields=['school', 'school_class', 'is_active'], name='idx_supplyreq_school_class'),
        ),
        migrations.AddIndex(
            model_name='studentsupplycontribution',
            index=models.Index(fields=['item', 'student'], name='idx_supply_contrib_item_stu'),
        ),
        migrations.AddConstraint(
            model_name='studentsupplycontribution',
            constraint=models.UniqueConstraint(fields=('item', 'student'), name='uniq_supply_contrib_item_stu'),
        ),
    ]
