# Generated by Django 5.2.13 on 2026-05-12 01:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0063_alter_teacherattendance_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Running total of partial payments credited so far.', max_digits=10),
        ),
        migrations.AddField(
            model_name='canteenpayment',
            name='daily_units',
            field=models.PositiveIntegerField(default=0, help_text='For daily frequency: number of days covered by this payment.'),
        ),
        migrations.AddField(
            model_name='canteenpayment',
            name='payment_frequency',
            field=models.CharField(choices=[('single', 'Single Payment'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('term', 'Per Term')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='canteenpayment',
            name='payment_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
