# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_add_quiz_and_term_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homework/attachments/'),
        ),
    ]
