# Generated by Django 6.0.3 on 2026-03-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_grading_system_models'),
        ('schools', '0007_remove_school_flutterwave_tx_ref_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradingpolicy',
            unique_together={('school', 'is_default')},
        ),
    ]
