# Generated by Django 6.0.3 on 2026-04-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_add_result_fields'),
        ('schools', '0007_remove_school_flutterwave_tx_ref_and_more'),
        ('students', '0008_add_exit_reason_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentresultsummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentresultsummary',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentresultsummary',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentresultsummary',
            name='term',
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Results'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='gradingpolicy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='room',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gradingpolicy',
            name='allows_decimal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gradingpolicy',
            name='max_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='gradingpolicy',
            name='pass_mark',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='gradingpolicy',
            name='use_custom_grades',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradingpolicy',
            name='use_weighted_averages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='students.student'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AlterField(
            model_name='examscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='students.student'),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homework/'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academics.quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='students.student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.examtype'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_name', 'day_of_week', 'start_time')},
        ),
        migrations.CreateModel(
            name='AIStudentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('comment_type', models.CharField(choices=[('academic', 'Academic Performance'), ('behavioral', 'Behavioral'), ('overall', 'Overall Summary')], max_length=20)),
                ('tone', models.CharField(choices=[('encouraging', 'Encouraging'), ('professional', 'Professional'), ('detailed', 'Detailed'), ('concise', 'Concise')], default='professional', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_comments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_comments', to='students.student')),
            ],
            options={
                'verbose_name': 'AI Student Comment',
                'verbose_name_plural': 'AI Student Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('feedback', models.TextField(blank=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_submissions', to='academics.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.CreateModel(
            name='OnlineMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=60)),
                ('meeting_link', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('host_url', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='GradePoint',
        ),
        migrations.DeleteModel(
            name='StudentResultSummary',
        ),
        migrations.RemoveField(
            model_name='gradingpolicy',
            name='ca_weight',
        ),
        migrations.RemoveField(
            model_name='gradingpolicy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gradingpolicy',
            name='exam_weight',
        ),
        migrations.RemoveField(
            model_name='gradingpolicy',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='gradingpolicy',
            name='name',
        ),
    ]
