# Generated by Django 6.0.3 on 2026-04-09 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_examtype_options_alter_result_options_and_more'),
        ('schools', '0008_alter_school_options_alter_schoolfeature_options'),
        ('students', '0009_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school', 'class_name', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='assessmentscore',
            index=models.Index(fields=['student', 'subject', 'term'], name='idx_ascore_stu_sub_term'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'class_name'], name='idx_hw_school_class'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'due_date'], name='idx_hw_school_due'),
        ),
        migrations.AddIndex(
            model_name='onlinemeeting',
            index=models.Index(fields=['school', 'scheduled_time'], name='idx_meeting_school_time'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'is_completed'], name='idx_quizatt_stu_done'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'exam_type', 'term'), name='uniq_result_stu_sub_exam_term'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('school',), name='unique_current_term_per_school'),
        ),
    ]
