# Generated by Django 6.0.3 on 2026-04-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_timetable_unique_together_and_more'),
        ('students', '0010_student_school_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'managed': True, 'ordering': ['level']},
        ),
        migrations.AddField(
            model_name='examschedule',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='homework',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_set', to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='onlinemeeting',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_meetings', to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='students.schoolclass'),
        ),
    ]
