# Generated by Django 6.0.3 on 2026-04-09 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_studentclass_options_examschedule_school_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homework/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
