# Generated by Django 6.0.3 on 2026-04-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_quiz_answer_and_correct_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts_per_student',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many times each student may complete this quiz.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=50, help_text='Minimum percentage (0–100) to pass.'),
        ),
    ]
