# Generated by Django 5.2.13 on 2026-04-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_fix_grading_models'),
        ('academics', '0019_quiz_max_attempts'),
    ]

    operations = [
    ]
