# Generated by Django 5.2.13 on 2026-04-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_merge_0015_fix_grading_models_0019_quiz_max_attempts'),
        ('schools', '0011_erp_enhancements_batch1'),
        ('students', '0014_studentclearance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingpolicy',
            options={'verbose_name': 'Grading Policy', 'verbose_name_plural': 'Grading Policies'},
        ),
        migrations.AlterModelOptions(
            name='studentresultsummary',
            options={'ordering': ['term', 'student'], 'verbose_name': 'Student Result Summary', 'verbose_name_plural': 'Student Result Summaries'},
        ),
        migrations.AlterField(
            model_name='gradepoint',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], max_length=5),
        ),
        migrations.AlterField(
            model_name='gradepoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gradepoint',
            name='scale',
            field=models.CharField(choices=[('5.0', '5.0 Scale'), ('4.0', '4.0 Scale')], default='5.0', max_length=5),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='ca_weight',
            field=models.FloatField(default=50.0, help_text='Continuous Assessment weight %'),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='exam_weight',
            field=models.FloatField(default=50.0, help_text='End-of-term Exam weight %'),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_policies', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='use_weighted_averages',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentresultsummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentresultsummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_summaries', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='gradepoint',
            unique_together={('school', 'grade', 'scale')},
        ),
        migrations.AlterUniqueTogether(
            name='studentresultsummary',
            unique_together={('student', 'subject', 'term')},
        ),
    ]
