# Generated by Django 5.2.13 on 2026-04-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_create_studentresultsummary'),
        ('academics', '0021_add_ai_student_comment'),
    ]

    operations = [
    ]
