# Generated by Django 5.2.13 on 2026-04-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0051_timetable_teacher_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_results_immediately',
            field=models.BooleanField(default=True, help_text='Show score and correct answers to students right after submission.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Optional open window start. If blank, quiz is open immediately when active.', null=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='teacher_reviewed',
            field=models.BooleanField(default=True, help_text='False for essay answers until a teacher enters marks.'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='tab_blur_count',
            field=models.PositiveIntegerField(default=0, help_text='How often the quiz tab lost visibility during this attempt (honesty signal).'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='match_left',
            field=models.TextField(blank=True, help_text='Pipe-separated left-side items for matching questions.'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='match_right',
            field=models.TextField(blank=True, help_text='Pipe-separated right-side items for matching questions.'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_e',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_f',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marks deducted per wrong selected answer for multi_select (0 = no penalty).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='A–D for MCQ/T-F/dropdown; comma-separated for multi_select (e.g. A,C); JSON pairs for matching.', max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('multi_select', 'Multi-Select (Checkboxes)'), ('dropdown', 'Dropdown'), ('matching', 'Matching')], default='multiple_choice', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
