# Generated by Django 5.2.13 on 2026-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0055_academicyear_term_subject_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Only one year per school should be current. Saving with True auto-unsets others.'),
        ),
    ]
