# Generated by Django 5.2.13 on 2026-04-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0057_student_transcript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworksubmission',
            options={'managed': False, 'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='studentclass',
            options={'managed': False, 'ordering': ['level']},
        ),
    ]
