# Generated by Django 5.2.13 on 2026-04-27 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0059_result_school_non_nullable'),
        ('schools', '0018_school_currency'),
        ('students', '0019_student_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentscore',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Denormalised from student.school for direct tenant-scoped queries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='schools.school'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Denormalised from student.school for direct tenant-scoped queries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='schools.school'),
        ),
        migrations.AddField(
            model_name='result',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete: result is hidden from students/parents but not erased.', null=True),
        ),
        migrations.AddField(
            model_name='studentresultsummary',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Denormalised from student.school for direct tenant-scoped queries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_summaries', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='assessmentscore',
            index=models.Index(fields=['school', 'term'], name='idx_ascore_school_term'),
        ),
    ]
