# Generated by Django 5.2.13 on 2026-04-28 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0060_assessmentscore_school_examscore_school_and_more'),
        ('schools', '0018_school_currency'),
        ('students', '0019_student_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Mathematics Form 2 — Algebra'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False, help_text='When True, any teacher in the school can use this bank.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Question Bank',
                'verbose_name_plural': 'Question Banks',
                'ordering': ['subject__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, help_text="Sub-topic within the subject (e.g. 'Quadratic Equations')", max_length=200)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('multi_select', 'Multi-Select'), ('matching', 'Matching')], default='multiple_choice', max_length=20)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('option_e', models.CharField(blank=True, max_length=500)),
                ('option_f', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.CharField(blank=True, help_text='A–F for MCQ; comma-separated for multi_select; text for short_answer.', max_length=500)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('bloom_level', models.CharField(blank=True, choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], max_length=20)),
                ('explanation', models.TextField(blank=True, help_text='Model answer / marking guide shown after submission.')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Counter incremented when imported into an exam.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academics.questionbank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_items', to='schools.school')),
            ],
            options={
                'verbose_name': 'Question Bank Item',
                'verbose_name_plural': 'Question Bank Items',
                'ordering': ['bank', 'topic', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF file stored on the file system / Supabase.', null=True, upload_to='report_cards/%Y/%m/')),
                ('qr_token', models.CharField(help_text='Random token used in QR-code URL for verification.', max_length=64, unique=True)),
                ('is_latest', models.BooleanField(db_index=True, default=True, help_text='Only the most recent generation per student/term should be True.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(db_index=True, default=False, help_text='When True, parents/students can download. Set by the class teacher or admin.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('principal_remarks', models.TextField(blank=True)),
                ('class_teacher_remarks', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards', to='academics.academicyear')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards', to='academics.term')),
            ],
            options={
                'verbose_name': 'Report Card',
                'verbose_name_plural': 'Report Cards',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='EarlyWarningFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('trigger_type', models.CharField(choices=[('attendance', 'Poor Attendance'), ('results', 'Declining Results'), ('discipline', 'Discipline Incidents'), ('composite', 'Multiple Factors'), ('manual', 'Manually Raised')], default='composite', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured evidence dict e.g. {"attendance_rate": 68, "avg_score_drop": 15, "discipline_count": 2}')),
                ('notes', models.TextField(blank=True, help_text='Teacher/admin notes or action plan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(blank=True, db_index=True, max_length=20)),
                ('term', models.CharField(blank=True, max_length=20)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_warnings_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, help_text='Set for manually raised flags; null for system-generated ones.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_warnings_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_warnings_resolved', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_warnings', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_warnings', to='students.student')),
            ],
            options={
                'verbose_name': 'Early Warning Flag',
                'verbose_name_plural': 'Early Warning Flags',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'risk_level', 'status'], name='idx_ewflag_school_risk_status'), models.Index(fields=['school', 'created_at'], name='idx_ewflag_school_ts')],
            },
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['school', 'subject'], name='idx_qbank_school_subject'),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['school', 'difficulty'], name='idx_qbankitem_school_diff'),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['bank', 'topic'], name='idx_qbankitem_bank_topic'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['school', 'student', 'is_latest'], name='idx_rc_school_stu_latest'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['school', 'published'], name='idx_rc_school_pub'),
        ),
    ]
