# Generated by Django 5.2.13 on 2026-05-03 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0062_examschedule_optional_time_venue'),
        ('schools', '0020_alter_schoolfeature_key_choices'),
        ('students', '0020_erp_new_models_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='Class this scheme applies to.', max_length=100)),
                ('ca_weight', models.FloatField(default=50.0, help_text='CA contribution to final score (%).')),
                ('exam_weight', models.FloatField(default=50.0, help_text='Exam contribution to final score (%).')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_schemes', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schemes', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schemes', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schemes', to='academics.term')),
            ],
            options={
                'verbose_name': 'Assessment Scheme',
                'verbose_name_plural': 'Assessment Schemes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSchemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment / Homework'), ('class_test', 'Class Test'), ('manual_ca', 'Manual CA Entry'), ('other_ca', 'Other CA'), ('online_exam', 'Online Exam'), ('omr_exam', 'OMR Exam (Section A only)'), ('omr_combined', 'OMR Exam (Section A + Section B)'), ('manual_exam', 'Manual Offline Exam'), ('imported_exam', 'Imported Exam Score')], max_length=20)),
                ('source_id', models.IntegerField(blank=True, help_text='PK of the related OmrExam / Quiz / ManualExamScore / etc. record.', null=True)),
                ('category', models.CharField(choices=[('ca', 'Continuous Assessment'), ('exam', 'Exam')], max_length=5)),
                ('label', models.CharField(help_text='Human-readable display name for this item.', max_length=200)),
                ('max_score', models.FloatField(default=100.0, help_text='Maximum possible raw score for this item.')),
                ('include_in_report_card', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academics.assessmentscheme')),
            ],
            options={
                'verbose_name': 'Assessment Scheme Item',
                'verbose_name_plural': 'Assessment Scheme Items',
                'ordering': ['category', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManualExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=100)),
                ('max_score', models.FloatField(default=100.0)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_exam_scores', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_exam_scores', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_exam_scores', to='academics.term')),
            ],
            options={
                'verbose_name': 'Manual Exam',
                'verbose_name_plural': 'Manual Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualExamStudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='academics.manualexamscore')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_exam_student_scores', to='students.student')),
            ],
            options={
                'verbose_name': 'Manual Exam Student Score',
                'ordering': ['student__admission_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentReportCardScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_raw_score', models.FloatField(default=0)),
                ('ca_total_possible', models.FloatField(default=0)),
                ('ca_contribution', models.FloatField(default=0, help_text='Out of ca_weight (e.g. 50).')),
                ('exam_raw_score', models.FloatField(default=0)),
                ('exam_total_possible', models.FloatField(default=0)),
                ('exam_contribution', models.FloatField(default=0, help_text='Out of exam_weight (e.g. 50).')),
                ('final_score', models.FloatField(default=0, help_text='ca_contribution + exam_contribution.')),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete — missing sources'), ('pending', 'Pending calculation')], db_index=True, default='pending', max_length=15)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_card_scores', to='academics.assessmentscheme')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_scores', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_scores', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_scores', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_scores', to='academics.term')),
            ],
            options={
                'verbose_name': 'Student Report Card Score',
                'verbose_name_plural': 'Student Report Card Scores',
                'ordering': ['student__admission_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentscheme',
            constraint=models.UniqueConstraint(fields=('school', 'class_name', 'subject', 'term'), name='uniq_scheme_school_class_subj_term'),
        ),
        migrations.AddConstraint(
            model_name='manualexamscore',
            constraint=models.UniqueConstraint(fields=('school', 'exam_title', 'subject', 'term', 'class_name'), name='uniq_manualexam_school_title_subj_term_class'),
        ),
        migrations.AlterUniqueTogether(
            name='manualexamstudentscore',
            unique_together={('exam', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentreportcardscore',
            index=models.Index(fields=['school', 'term'], name='idx_rcscore_school_term'),
        ),
        migrations.AddIndex(
            model_name='studentreportcardscore',
            index=models.Index(fields=['school', 'status'], name='idx_rcscore_school_status'),
        ),
        migrations.AlterUniqueTogether(
            name='studentreportcardscore',
            unique_together={('student', 'subject', 'term')},
        ),
    ]
