# Generated by Django 5.2.13 on 2026-05-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0063_assessmentscheme_assessmentschemeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlywarningflag',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlywarningflag',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
