# Generated by Django 5.2.13 on 2026-04-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_broadcastnotification_target_class_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastnotification',
            name='target_class',
            field=models.CharField(blank=True, help_text='Legacy: Target class for class-wide broadcasts. Prefer target_class_fk.', max_length=50),
        ),
    ]
