# Generated by Django 5.2.13 on 2026-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_school_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('payment', 'Payment'), ('attendance', 'Attendance'), ('result', 'Result'), ('message', 'Message'), ('inventory_alert', 'Inventory Alert'), ('leave_approved', 'Leave Approved'), ('purchase_order', 'Purchase Order'), ('subscription', 'Subscription')], default='info', max_length=20),
        ),
    ]
