# Generated by Django 5.2.13 on 2026-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='academic_event_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='contract_expiry_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='fee_reminder_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='installment_overdue_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='inventory_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='leave_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='muted_until',
            field=models.DateTimeField(blank=True, help_text='Snooze all in-app notifications until this timestamp.', null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='purchase_order_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='subscription_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('payment', 'Payment'), ('attendance', 'Attendance'), ('result', 'Result'), ('message', 'Message'), ('inventory_alert', 'Inventory Alert'), ('leave_approved', 'Leave Approved'), ('purchase_order', 'Purchase Order'), ('subscription', 'Subscription'), ('fee_reminder', 'Fee Reminder'), ('academic_event', 'Academic Event'), ('contract_expiry', 'Contract Expiry'), ('installment_overdue', 'Installment Overdue')], default='info', max_length=20),
        ),
    ]
