# Generated by Django 6.0.3 on 2026-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_role_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
