# Generated by Django 6.0.3 on 2026-04-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_examtype_options_alter_result_options_and_more'),
        ('accounts', '0011_fix_profile_photo_urlfield'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0008_alter_school_options_alter_schoolfeature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'Headteacher/Admin'), ('deputy_head', 'Deputy Headteacher'), ('hod', 'Head of Department'), ('teacher', 'Teacher'), ('accountant', 'Accountant/Bursar'), ('librarian', 'Librarian'), ('admission_officer', 'Admission Officer'), ('school_nurse', 'School Nurse'), ('admin_assistant', 'Admin Assistant'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, default='parent', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school', 'role'], name='idx_user_school_role'),
        ),
    ]
