# Generated by Django 6.0.3 on 2026-04-09 10:42
#
# Database operations are idempotent: production DBs may already have `gender`
# or `idx_user_school_role` from manual changes or partial deploys.

from django.db import migrations, models


def _ensure_gender_column(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        if conn.vendor == "postgresql":
            cursor.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = 'accounts_user'
                  AND column_name = 'gender'
                """
            )
            if cursor.fetchone():
                return
            cursor.execute("ALTER TABLE accounts_user ADD COLUMN gender VARCHAR(10) NULL")
        elif conn.vendor == "sqlite":
            cursor.execute("PRAGMA table_info(accounts_user)")
            if any(row[1] == "gender" for row in cursor.fetchall()):
                return
            cursor.execute("ALTER TABLE accounts_user ADD COLUMN gender VARCHAR(10) NULL")


def _ensure_school_role_index(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        if conn.vendor == "postgresql":
            cursor.execute(
                "SELECT 1 FROM pg_indexes WHERE indexname = 'idx_user_school_role'"
            )
            if cursor.fetchone():
                return
            cursor.execute(
                "CREATE INDEX idx_user_school_role ON accounts_user (school_id, role)"
            )
        elif conn.vendor == "sqlite":
            cursor.execute(
                "SELECT 1 FROM sqlite_master WHERE type = 'index' AND name = 'idx_user_school_role'"
            )
            if cursor.fetchone():
                return
            cursor.execute(
                "CREATE INDEX idx_user_school_role ON accounts_user (school_id, role)"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0014_alter_examtype_options_alter_result_options_and_more"),
        ("accounts", "0011_fix_profile_photo_urlfield"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("schools", "0008_alter_school_options_alter_schoolfeature_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(_ensure_gender_column, migrations.RunPython.noop),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("school_admin", "Headteacher/Admin"),
                    ("deputy_head", "Deputy Headteacher"),
                    ("hod", "Head of Department"),
                    ("teacher", "Teacher"),
                    ("accountant", "Accountant/Bursar"),
                    ("librarian", "Librarian"),
                    ("admission_officer", "Admission Officer"),
                    ("school_nurse", "School Nurse"),
                    ("admin_assistant", "Admin Assistant"),
                    ("staff", "Staff"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                ],
                db_index=True,
                default="parent",
                max_length=20,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="user",
                    index=models.Index(fields=["school", "role"], name="idx_user_school_role"),
                ),
            ],
            database_operations=[
                migrations.RunPython(_ensure_school_role_index, migrations.RunPython.noop),
            ],
        ),
    ]
