# Generated by Django 6.0.3 on 2026-04-09 14:14
#
# Idempotent: column may already exist on databases that were patched manually.

from django.db import migrations, models


def _ensure_must_change_password(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        if conn.vendor == "postgresql":
            cursor.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = 'accounts_user'
                  AND column_name = 'must_change_password'
                """
            )
            if cursor.fetchone():
                return
            cursor.execute(
                "ALTER TABLE accounts_user ADD COLUMN must_change_password boolean NOT NULL DEFAULT false"
            )
        elif conn.vendor == "sqlite":
            cursor.execute("PRAGMA table_info(accounts_user)")
            if any(row[1] == "must_change_password" for row in cursor.fetchall()):
                return
            cursor.execute(
                "ALTER TABLE accounts_user ADD COLUMN must_change_password bool NOT NULL DEFAULT 0"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_user_options_user_gender_alter_user_role_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="must_change_password",
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[
                migrations.RunPython(_ensure_must_change_password, migrations.RunPython.noop),
            ],
        ),
    ]
