# Generated by Django 6.0.3 on 2026-04-11 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_quiz_max_attempts'),
        ('accounts', '0013_security_must_change_password'),
        ('schools', '0009_alter_schoolfeature_key_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed term'), ('temporary', 'Temporary'), ('probation', 'Probation'), ('consultant', 'Consultant / part-time')], default='fixed_term', max_length=20)),
                ('job_title', models.CharField(blank=True, help_text='e.g. Senior Mathematics Teacher', max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for open-ended.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_contracts', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['school', 'user', 'status'], name='idx_staffcontract_school_user')],
            },
        ),
        migrations.CreateModel(
            name='StaffPayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text='e.g. January 2026, Week 3', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=8)),
                ('paid_on', models.DateField()),
                ('method', models.CharField(choices=[('bank', 'Bank transfer'), ('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payroll_payments', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payroll_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
                'indexes': [models.Index(fields=['school', 'user', 'paid_on'], name='idx_staffpay_school_user_date')],
            },
        ),
        migrations.CreateModel(
            name='StaffRoleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_kind', models.CharField(choices=[('primary', 'Primary role'), ('secondary', 'Secondary roles')], max_length=20)),
                ('from_value', models.CharField(blank=True, help_text='Previous role key or CSV of secondary roles', max_length=200)),
                ('to_value', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role_logs', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['school', 'user'], name='idx_staffrolelog_school_user')],
            },
        ),
        migrations.CreateModel(
            name='StaffTeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='Must match a class name in your school (e.g. Form 1A).', max_length=100)),
                ('academic_year', models.CharField(blank=True, help_text='e.g. 2025/2026', max_length=32)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, help_text='Empty means current / ongoing.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_teaching_assignments', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='academics.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'class_name', 'subject__name'],
                'indexes': [models.Index(fields=['school', 'user', 'is_active'], name='idx_staffteach_school_user_act')],
            },
        ),
    ]
