# Generated by Django 6.0.3 on 2026-04-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_staff_hr_models'),
        ('schools', '0009_alter_schoolfeature_key_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayrollpayment',
            name='paystack_failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffpayrollpayment',
            name='paystack_status',
            field=models.CharField(blank=True, choices=[('', 'Not sent via Paystack'), ('pending', 'Transfer queued / processing'), ('success', 'Transfer successful'), ('failed', 'Transfer failed')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='staffpayrollpayment',
            name='paystack_transfer_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='staffpayrollpayment',
            name='recipient_snapshot',
            field=models.CharField(blank=True, help_text='Masked payout destination at time of transfer (audit)', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='payroll_bank_account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='payroll_bank_account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='payroll_bank_code',
            field=models.CharField(blank=True, default='', help_text='Paystack Ghana bank code for transfers (see Paystack dashboard / bank list)', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='payroll_momo_network',
            field=models.CharField(blank=True, choices=[('', '—'), ('MTN', 'MTN Mobile Money'), ('VOD', 'Telecel Cash'), ('ATL', 'AirtelTigo Money')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='payroll_momo_number',
            field=models.CharField(blank=True, default='', help_text='Digits only — used for Paystack mobile-money salary payouts', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_recipient_bank',
            field=models.CharField(blank=True, default='', help_text='Cached Paystack RCP for bank (NUBAN) payouts', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_recipient_momo',
            field=models.CharField(blank=True, default='', help_text='Cached Paystack RCP for mobile-money payouts', max_length=64),
        ),
        migrations.AddIndex(
            model_name='staffpayrollpayment',
            index=models.Index(fields=['reference'], name='idx_staffpay_reference'),
        ),
    ]
