# Generated by Django 6.0.3 on 2026-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_staff_payroll_payout_and_paystack'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setup_checklist_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
