# Generated by Django 5.2.13 on 2026-04-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_hr_erp_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='allocated_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total days allocated for this year (from policy + any manual adjustments).', max_digits=5),
        ),
    ]
