# Generated by Django 5.2.13 on 2026-04-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_leavebalance_allocated_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_backup_codes',
            field=models.TextField(blank=True, default='', help_text='Newline-separated one-time backup codes (hashed).'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='True when 2FA has been verified and activated by the user.'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', help_text='Base32 TOTP secret. Empty = 2FA not set up.', max_length=64),
        ),
    ]
