# Generated by Django 5.2.13 on 2026-04-27 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_totp_2fa_fields'),
        ('schools', '0018_school_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(choices=[('annual', 'Annual'), ('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3'), ('probation', 'Probation Review')], default='annual', max_length=20)),
                ('academic_year', models.CharField(help_text='e.g. 2025/2026', max_length=9)),
                ('punctuality_score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('teaching_quality_score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('communication_score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('initiative_score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('teamwork_score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unsatisfactory'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('goals_next_period', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('staff_acknowledgement', models.BooleanField(default=False)),
                ('staff_comments', models.TextField(blank=True)),
                ('is_finalised', models.BooleanField(db_index=True, default=False)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='schools.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Performance Review',
                'verbose_name_plural': 'Staff Performance Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'academic_year'], name='idx_staffreview_school_year')],
                'constraints': [models.UniqueConstraint(fields=('school', 'staff', 'review_period', 'academic_year'), name='uniq_staffreview_school_staff_period_year')],
            },
        ),
    ]
