# Generated by Django 5.2.14 on 2026-05-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_secondary_role_through_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'Headteacher/Admin'), ('deputy_head', 'Deputy Headteacher'), ('hod', 'Head of Department'), ('teacher', 'Teacher'), ('accountant', 'Accountant/Bursar'), ('librarian', 'Librarian'), ('admission_officer', 'Admission Officer'), ('exam_officer', 'Exam Officer'), ('school_nurse', 'School Nurse'), ('admin_assistant', 'Admin Assistant'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, default='parent', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersecondaryrole',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'Headteacher/Admin'), ('deputy_head', 'Deputy Headteacher'), ('hod', 'Head of Department'), ('teacher', 'Teacher'), ('accountant', 'Accountant/Bursar'), ('librarian', 'Librarian'), ('admission_officer', 'Admission Officer'), ('exam_officer', 'Exam Officer'), ('school_nurse', 'School Nurse'), ('admin_assistant', 'Admin Assistant'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, max_length=30),
        ),
    ]
