# Generated by Django 5.2.13 on 2026-05-09 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_user_role_alter_usersecondaryrole_role'),
        ('schools', '0020_alter_schoolfeature_key_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reason', models.CharField(choices=[('no_contact', 'No email or phone number'), ('lost_access', 'Lost access to email/phone'), ('technical_issue', 'Technical issue with reset'), ('other', 'Other reason')], default='no_contact', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Additional details about the reset request')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the decision')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reset_requests', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Password Reset Request',
                'verbose_name_plural': 'Admin Password Reset Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='idx_school_status'), models.Index(fields=['requested_at'], name='idx_requested_at')],
            },
        ),
    ]
