# Generated by Django 6.0.3 on 2026-03-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_add_partial_payments_subscription_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='flutterwave_tx_ref',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='stripe_payment_id',
        ),
    ]
