# Generated by Django 6.0.3 on 2026-04-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_fee_flutterwave_tx_ref_and_more'),
        ('schools', '0008_alter_school_options_alter_schoolfeature_options'),
        ('students', '0009_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fee', 'verbose_name_plural': 'Fees'},
        ),
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fee Payment', 'verbose_name_plural': 'Fee Payments'},
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='paystack_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['school', 'student'], name='idx_fee_school_student'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['school', 'paid'], name='idx_fee_school_paid'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['student', 'paid'], name='idx_fee_student_paid'),
        ),
    ]
