# Generated by Django 6.0.3 on 2026-04-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_timetable_unique_together_and_more'),
        ('finance', '0005_alter_fee_options_alter_feepayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_structure',
            field=models.ForeignKey(blank=True, help_text='Fee type this charge originated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='fee',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Academic term this fee belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='academics.term'),
        ),
    ]
