# Generated by Django 6.0.3 on 2026-04-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_fee_fee_structure_fee_term'),
        ('students', '0010_student_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='students.schoolclass'),
        ),
    ]
