# Generated by Django 6.0.3 on 2026-04-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_feestructure_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total charged on Paystack (includes uplift when pass-fee-to-payer is on).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Net amount credited to the fee balance (excluding processing uplift).', max_digits=12),
        ),
    ]
