# Generated by Django 5.2.13 on 2026-04-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_feepayment_payer_notified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payer_notified_at',
            field=models.DateTimeField(blank=True, help_text='Set when payer SMS/email was sent; prevents duplicate notices from webhook+callback.', null=True),
        ),
    ]
