# Generated by Django 5.2.13 on 2026-04-19 22:34

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_paymenttransaction_review_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fee',
            managers=[
                ('scoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='feestructure',
            managers=[
                ('scoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subscriptionpayment',
            managers=[
                ('scoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
