# Generated by Django 5.2.13 on 2026-04-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_staffpayoutrequest'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fee',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='feestructure',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='subscriptionpayment',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='schoolfundsbalance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schoolfundsledgerentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffpayoutrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
