# Generated by Django 5.2.13 on 2026-04-27 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_feepayment_school_index'),
        ('schools', '0015_school_timezone_email_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Denormalised for fast cross-school queries; kept in sync on save.', null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
