# Generated by Django 5.2.13 on 2026-04-27 10:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_paystack_settlement'),
        ('operations', '0058_alter_teacherattendance_teacher'),
        ('schools', '0018_school_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, help_text='Auto-generated reference', max_length=50)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_contact', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('ordered', 'Ordered from Supplier'), ('received', 'Goods Received'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('linked_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order', to='operations.expense')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_requested', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='schools.school')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='operations.inventoryitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.purchaseorder')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='schools.school')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('account_type', models.CharField(choices=[('fees', 'Fees Collection'), ('salary', 'Salary Disbursement'), ('petty_cash', 'Petty Cash'), ('investment', 'Investment'), ('other', 'Other')], default='fees', max_length=20)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='schools.school')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'indexes': [models.Index(fields=['school', 'account_type'], name='idx_bankacct_school_type')],
                'constraints': [models.UniqueConstraint(fields=('school', 'account_number', 'bank_name'), name='uniq_bankaccount_school_number_bank')],
            },
        ),
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('sibling', 'Sibling Discount'), ('merit', 'Merit Award'), ('hardship', 'Hardship Waiver'), ('staff_child', 'Staff Child Benefit'), ('other', 'Other')], max_length=30)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage off the fee amount (0–100).', max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed GHS amount to discount (used if percentage is blank).', max_digits=12, null=True)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discounts', to=settings.AUTH_USER_MODEL)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='finance.fee')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_discounts', to='schools.school')),
            ],
            options={
                'verbose_name': 'Fee Discount',
                'verbose_name_plural': 'Fee Discounts',
                'indexes': [models.Index(fields=['school', 'discount_type'], name='idx_feediscount_school_type')],
            },
        ),
        migrations.CreateModel(
            name='FeeInstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='finance.fee')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='schools.school')),
            ],
            options={
                'verbose_name': 'Fee Installment',
                'verbose_name_plural': 'Fee Installments',
                'ordering': ['installment_number'],
                'indexes': [models.Index(fields=['school', 'status', 'due_date'], name='idx_install_school_status_due')],
                'constraints': [models.UniqueConstraint(fields=('fee', 'installment_number'), name='uniq_installment_fee_num')],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['school', 'status'], name='idx_po_school_status'),
        ),
    ]
