# Generated by Django 5.2.13 on 2026-04-27 11:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0060_assessmentscore_school_examscore_school_and_more'),
        ('finance', '0028_purchaseorder_purchaseorderitem_bankaccount_and_more'),
        ('schools', '0018_school_currency'),
        ('students', '0019_student_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('workflow_type', models.CharField(choices=[('expense', 'Expense Approval'), ('purchase_order', 'Purchase Order Approval'), ('leave', 'Leave Request Approval'), ('payroll', 'Payroll Approval'), ('custom', 'Custom')], db_index=True, default='custom', max_length=30)),
                ('steps', models.JSONField(default=list, help_text='Ordered list of approval steps: [{"step": 1, "role": "bursar", "label": "Finance check"}]. Supported role values match User.role choices.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'ordering': ['school', 'workflow_type'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(help_text='Unique asset identifier (e.g. FA-2025-001)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('land', 'Land & Buildings'), ('furniture', 'Furniture & Fittings'), ('it_equipment', 'IT Equipment'), ('vehicles', 'Vehicles'), ('lab_equipment', 'Lab Equipment'), ('sports_equipment', 'Sports Equipment'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=5, help_text='Estimated lifespan for straight-line depreciation.')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('current_book_value', models.DecimalField(decimal_places=2, help_text='Updated annually by the depreciation task.', max_digits=14)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('written_off', 'Written Off')], db_index=True, default='good', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='False = disposed/written off.')),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'ordering': ['school', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='app_label.ModelName of the subject', max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('history', models.JSONField(default=list, help_text='Append-only list of step outcomes: [{"step": 1, "actor": 5, "action": "approved", "note": "", "ts": "..."}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow Instance',
                'verbose_name_plural': 'Workflow Instances',
            },
        ),
        migrations.AddField(
            model_name='fee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete timestamp. Non-null = archived fee.', null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.CharField(blank=True, help_text="Optional human-readable label (e.g. 'Term 1 School Fees 2025').", max_length=255),
        ),
        migrations.AddField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date by which payment is expected. Used for reminders and overdue tracking.', null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive fees are archived and excluded from reminders.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total_amount + tax_amount', max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='VAT/tax rate as percentage (e.g. 15.00 for 15%).', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['school', 'due_date', 'is_active'], name='idx_fee_school_due_active'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='schools.school'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='linked_purchase_order',
            field=models.ForeignKey(blank=True, help_text='Procurement PO that brought this asset into service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='finance.purchaseorder'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='schools.school'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='schools.school'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='finance.approvalworkflow'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflow',
            unique_together={('school', 'workflow_type')},
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['school', 'category'], name='idx_fasset_school_cat'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['school', 'is_active'], name='idx_fasset_school_active'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['school', 'status'], name='idx_wfinst_school_status'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_wfinst_ct_obj'),
        ),
    ]
