# Generated by Django 5.2.13 on 2026-04-28 11:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_paymenttransaction_content_type_fk'),
        ('schools', '0018_school_currency'),
        ('students', '0019_student_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scholarship_type', models.CharField(choices=[('merit', 'Academic Merit'), ('sports', 'Sports Excellence'), ('bursary', 'Financial Bursary / Hardship'), ('donor', 'Donor / Sponsored'), ('staff_child', 'Staff Child Benefit'), ('government', 'Government Grant'), ('other', 'Other')], default='merit', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Minimum GPA, income threshold, sport performance, etc.')),
                ('cycle', models.CharField(choices=[('annual', 'Annual'), ('termly', 'Per Term'), ('one_off', 'One-Off')], default='annual', max_length=10)),
                ('academic_year', models.CharField(blank=True, help_text="e.g. '2025/2026'", max_length=20)),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total GHS budgeted for this scholarship programme.', max_digits=14)),
                ('amount_per_award', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Default award value per recipient (can be overridden per award).', max_digits=12)),
                ('percentage_off', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: % fee reduction rather than fixed GHS amount.', max_digits=5, null=True)),
                ('max_recipients', models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of students who can receive this scholarship.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='schools.school')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('term', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_fee_discount', models.OneToOneField(blank=True, help_text='Auto-created FeeDiscount row when award is activated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarship_award', to='finance.feediscount')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='finance.scholarship')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_awards', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_awards', to='students.student')),
            ],
            options={
                'verbose_name': 'Scholarship Award',
                'verbose_name_plural': 'Scholarship Awards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['school', 'scholarship_type'], name='idx_schol_school_type'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['school', 'is_active'], name='idx_schol_school_active'),
        ),
        migrations.AddIndex(
            model_name='scholarshipaward',
            index=models.Index(fields=['school', 'status'], name='idx_saward_school_status'),
        ),
    ]
