# Generated by Django 5.2.13 on 2026-05-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0036_feepayment_void_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='refund_failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('requested', 'Refund requested'), ('processed', 'Refund processed'), ('failed', 'Refund failed')], db_index=True, default='', help_text='Two-phase refund state. Empty until a refund is requested.', max_length=20),
        ),
    ]
