# Generated by Django 6.0.3 on 2026-03-31 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0007_remove_school_flutterwave_tx_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'Viewed'), ('export', 'Exported'), ('import', 'Imported')], max_length=20)),
                ('model_name', models.CharField(help_text='Name of the model affected', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the affected object', max_length=255, null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dictionary of field changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='schools.school')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['model_name', 'timestamp'], name='audit_audit_model_n_8d2a32_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['school', 'timestamp'], name='audit_audit_school__c0fedb_idx')],
            },
        ),
    ]
