# Generated by Django 5.2.13 on 2026-04-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_gdpr_export_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gdprexportrequest',
            new_name='audit_gdpre_school__316598_idx',
            old_name='idx_gdpr_school_status',
        ),
    ]
