# Generated by Django 5.2.13 on 2026-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_rename_idx_gdpr_school_status_audit_gdpre_school__316598_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('2fa_verified', '2FA Verified'), ('2fa_failed', '2FA Failed'), ('password_change', 'Password Changed'), ('view', 'Viewed'), ('export', 'Exported'), ('gdpr_export', 'GDPR Export'), ('import', 'Imported'), ('approve', 'Approved'), ('reject', 'Rejected')], max_length=20),
        ),
    ]
