# Generated by Django 6.0.3 on 2026-03-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_absencerequest_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
