# Generated by Django 6.0.3 on 2026-03-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_quiz_and_term_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exit_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the exit'),
        ),
        migrations.AddField(
            model_name='student',
            name='exit_reason',
            field=models.CharField(blank=True, help_text='Reason for exit: graduated, left, transferred, suspended, expelled, deceased', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated / Alumni'), ('withdrawn', 'Withdrawn / Transferred'), ('dismissed', 'Dismissed / Expelled'), ('suspended', 'Suspended'), ('deceased', 'Deceased')], default='active', help_text='Use this instead of deleting students so history is preserved.', max_length=20),
        ),
    ]
