# Generated by Django 6.0.3 on 2026-04-09 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_school_options_alter_schoolfeature_options'),
        ('students', '0008_add_exit_reason_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['school_admin', 'teacher']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_name'], name='idx_student_school_class'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'status'], name='idx_student_school_status'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['parent'], name='idx_student_parent'),
        ),
    ]
