# Generated by Django 6.0.3 on 2026-04-09 13:04

from django.db import migrations


def backfill_school_class(apps, schema_editor):
    """Create SchoolClass records from existing class_name values and link them."""
    SchoolClass = apps.get_model("students", "SchoolClass")
    Student = apps.get_model("students", "Student")

    schools_classes = (
        Student.objects.filter(class_name__gt="")
        .values_list("school_id", "class_name")
        .distinct()
    )
    cache = {}
    for school_id, name in schools_classes:
        obj, _ = SchoolClass.objects.get_or_create(
            school_id=school_id, name=name, defaults={"capacity": 40}
        )
        cache[(school_id, name)] = obj.pk

    for (school_id, name), sc_pk in cache.items():
        Student.objects.filter(school_id=school_id, class_name=name, school_class__isnull=True).update(
            school_class_id=sc_pk
        )

    # Backfill academics models
    for model_label in [
        ("academics", "Homework"),
        ("academics", "ExamSchedule"),
        ("academics", "Timetable"),
        ("academics", "Quiz"),
        ("academics", "OnlineMeeting"),
    ]:
        Model = apps.get_model(*model_label)
        rows = Model.objects.filter(class_name__gt="").values_list("school_id", "class_name").distinct()
        for school_id, name in rows:
            sc, _ = SchoolClass.objects.get_or_create(
                school_id=school_id, name=name, defaults={"capacity": 40}
            )
            Model.objects.filter(school_id=school_id, class_name=name, school_class__isnull=True).update(
                school_class_id=sc.pk
            )

    # Backfill operations models
    for model_label in [
        ("operations", "TimetableSlot"),
        ("operations", "Alumni"),
    ]:
        Model = apps.get_model(*model_label)
        rows = Model.objects.filter(class_name__gt="").values_list("school_id", "class_name").distinct()
        for school_id, name in rows:
            sc, _ = SchoolClass.objects.get_or_create(
                school_id=school_id, name=name, defaults={"capacity": 40}
            )
            Model.objects.filter(school_id=school_id, class_name=name, school_class__isnull=True).update(
                school_class_id=sc.pk
            )

    # Backfill finance.FeeStructure
    FeeStructure = apps.get_model("finance", "FeeStructure")
    rows = FeeStructure.objects.filter(class_name__gt="").values_list("school_id", "class_name").distinct()
    for school_id, name in rows:
        sc, _ = SchoolClass.objects.get_or_create(
            school_id=school_id, name=name, defaults={"capacity": 40}
        )
        FeeStructure.objects.filter(school_id=school_id, class_name=name, school_class__isnull=True).update(
            school_class_id=sc.pk
        )


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_student_school_class"),
        ("academics", "0016_alter_studentclass_options_examschedule_school_class_and_more"),
        ("operations", "0019_alumni_school_class_timetableslot_school_class"),
        ("finance", "0007_feestructure_school_class"),
    ]

    operations = [
        migrations.RunPython(backfill_school_class, migrations.RunPython.noop),
    ]
