# Generated by Django 6.0.3 on 2026-04-11 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_absencerequest_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['school_admin', 'deputy_head', 'hod', 'teacher']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
