# Generated by Django 5.2.13 on 2026-04-27 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_school_ai_monthly_token_cap'),
        ('students', '0016_studentguardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentguardian',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Denormalised from student.school for efficient tenant-scoped queries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_guardians', to='schools.school'),
        ),
    ]
