# Generated by Django 5.2.13 on 2026-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_backfill_guardian_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when soft-deleted. Use restore() to undo. Hard delete via hard_delete().', null=True),
        ),
    ]
