# Generated by Django 5.2.13 on 2026-04-28 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_school_currency'),
        ('students', '0019_student_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('sen', 'Special Educational Needs (SEN)'), ('gifted', 'Gifted & Talented'), ('remedial', 'Remedial Support'), ('behavioural', 'Behavioural Support Plan'), ('other', 'Other')], default='sen', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], db_index=True, default='draft', max_length=20)),
                ('academic_year', models.CharField(help_text='e.g. 2025/2026', max_length=20)),
                ('start_date', models.DateField()),
                ('review_date', models.DateField(blank=True, help_text='Scheduled next review date.', null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('goals', models.TextField(help_text='Specific, measurable learning goals for this plan period.')),
                ('accommodations', models.TextField(blank=True, help_text='Classroom accommodations: extra time, seating, reader, etc.')),
                ('support_resources', models.TextField(blank=True, help_text='External or internal support: speech therapy, tutoring, etc.')),
                ('progress_notes', models.TextField(blank=True, help_text='Ongoing teacher/SENCO progress notes.')),
                ('parent_acknowledged', models.BooleanField(default=False, help_text='Set when parent/guardian has been briefed and agrees to the plan.')),
                ('parent_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_plans_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_plans_updated', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to='students.student')),
            ],
            options={
                'verbose_name': 'Learning Plan',
                'verbose_name_plural': 'Learning Plans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='idx_lplan_school_status'), models.Index(fields=['school', 'student'], name='idx_lplan_school_student'), models.Index(fields=['school', 'review_date'], name='idx_lplan_school_review')],
            },
        ),
    ]
